package c_link;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : fuzzy_log.h:188</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ChainAndEntry extends Structure {
	public int chain;
	public int entry;

	public ChainAndEntry() {
		super();
	}

	protected List<String> getFieldOrder() {
		return Arrays.asList("chain", "entry");
	}

	public ChainAndEntry(int chain, int entry) {
		super();
		this.chain = chain;
		this.entry = entry;
	}

	public ChainAndEntry(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends ChainAndEntry implements Structure.ByReference {

	};

	public static class ByValue extends ChainAndEntry implements Structure.ByValue {

	};
}
