package c_link;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : fuzzy_log.h:95</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class get_next_val extends Structure {
	/** C type : const uint8_t* */
	public Pointer data;
	/** C type : const fuzzy_log_location* */
	public c_link.fuzzy_log_location.ByReference locs;

	public get_next_val() {
		super();
	}

	protected List<String> getFieldOrder() {
		return Arrays.asList("data", "locs");
	}

	/**
	 * @param data C type : const uint8_t*<br>
	 * @param locs C type : const fuzzy_log_location*
	 */
	public get_next_val(Pointer data, c_link.fuzzy_log_location.ByReference locs) {
		super();
		this.data = data;
		this.locs = locs;
	}

	public get_next_val(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends get_next_val implements Structure.ByReference {

	};

	public static class ByValue extends get_next_val implements Structure.ByValue {

	};
}
