package c_link;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : fuzzy_log.h:11</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class write_id extends Structure {
	public long p1;
	public long p2;

	public write_id() {
		super();
	}

	protected List<String> getFieldOrder() {
		return Arrays.asList("p1", "p2");
	}

	public write_id(long p1, long p2) {
		super();
		this.p1 = p1;
		this.p2 = p2;
	}

	public write_id(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends write_id implements Structure.ByReference {

	};

	public static class ByValue extends write_id implements Structure.ByValue {

	};
}
