package c_link;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : fuzzy_log.h:23</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class write_id_and_locs extends Structure {
	/** C type : write_id */
	public write_id id;
	/** C type : write_locations */
	public write_locations locations;

	public write_id_and_locs() {
		super();
	}

	protected List<String> getFieldOrder() {
		return Arrays.asList("id", "locations");
	}

	/**
	 * @param id C type : write_id<br>
	 * @param locations C type : write_locations
	 */
	public write_id_and_locs(write_id id, write_locations locations) {
		super();
		this.id = id;
		this.locations = locations;
	}

	public write_id_and_locs(Pointer peer) {
		super(peer);
	}

	public static class ByReference extends write_id_and_locs implements Structure.ByReference {

	};

	public static class ByValue extends write_id_and_locs implements Structure.ByValue {

	};
}
